name: Upload

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Zip Mod
      run: zip Tag_${{ github.ref_name }}.zip -r data pack.mcmeta LICENSE.md

    - name: Upload Result
      uses: sinshutu/upload-to-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: Tag_${{ github.ref_name }}.zip
